name: Bug report
description: Create a report
title: "[Bug]: "

body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: |
        Any language accepted
        아무 언어 사용가능
        すべての言語に対応
        接受所有语言
        Se aceptan todos los idiomas
        Alle Sprachen werden akzeptiert
        Toutes les langues sont acceptées
        Принимаются все языки

  - type: textarea
    attributes:
      label: The entire console log, including python version information, webui version, commit hash, commandline arguments and error traces.
      description: |
        The full console log of your terminal.
        From `Python ..., Version: ..., Commit hash: ...` to the end.
      placeholder: |
        Python ...
        Version: ...
        Commit hash: ...
        Installing requirements
        ...

        Launching Web UI with arguments: ...
        [-] ADetailer initialized. version: ...
        ...
      render: Shell
    validations:
      required: true

  - type: textarea
    attributes:
      label: List of installed extensions
